version: '3.8'

services:
  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminadminadmin
      - DOCKER_INFLUXDB_INIT_ORG=my-org 
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
      target: fastapi
    ports:
      - 80:80
    volumes:
      - ./src/log/logs:/crypto/src/log/logs
    environment:
      - TZ=Europe/Warsaw

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
      target: scheduler
    volumes:
      - ./src/log/logs:/crypto/src/log/logs
    environment:
      - TZ=Europe/Warsaw

volumes:
  influxdb-storage:
